---
name: IPC-PerlSSH-Async
version: 0.06
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: 'Asynchronous wrapper around L<IPC::PerlSSH>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  IO::Async::Test: 0
  Test::More: 0
  Test::Refcount: 0
requires:
  IO::Async: 0.21
  IPC::PerlSSH::Base: 0.12
configure_requires:
  Module::Build: 0.35
provides:
  IPC::PerlSSH::Async:
    file: lib/IPC/PerlSSH/Async.pm
    version: 0.06
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
