---
name: IPC-PerlSSH-Async
version: 0.04
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: 'Asynchronous wrapper around L<IPC::PerlSSH>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::Async: 0.16
  IPC::PerlSSH::Base: 0
build_requires:
  IO::Async::Test: 0
  Test::More: 0
  Test::Refcount: 0
provides:
  IPC::PerlSSH::Async:
    file: lib/IPC/PerlSSH/Async.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
