---
abstract: 'Asynchronous wrapper around L<IPC::PerlSSH>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::Test: 0
  Test::More: 0
  Test::Refcount: 0
  Test::Warn: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-PerlSSH-Async
provides:
  IPC::PerlSSH::Async:
    file: lib/IPC/PerlSSH/Async.pm
    version: 0.07
requires:
  IO::Async: 0.21
  IO::Async::Process: 0.37
  IPC::PerlSSH::Base: 0.16
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
